[package]
name = "riscv-rt"
version = "0.1.3"
repository = "https://github.com/dvc94ch/riscv-rt"
authors = ["David Craven <david@craven.ch>"]
categories = ["embedded", "no-std"]
description = "Minimal runtime / startup for RISCV CPU's"
keywords = ["riscv", "runtime", "startup"]
license = "ISC"

[dependencies]
r0 = "^0.2.1"
riscv = { path = "../riscv" }

[build-dependencies]
rustc_version = "0.2.1"
chrono = "0.4.0"
